version: '3'
services:
    loterioma_engine:
        build: .docker/php
        container_name: loterioma_engine
        stdin_open: true
        tty: true
        ports:
          - 9902:80
        environment:
          - APACHE_DOCUMENT_ROOT=/var/www/html/public
        volumes:
          - .:/var/www/html

    loterioma_engine_qa:
        image: raspberryvision/phpqa:0.1.2-stretch
        container_name: loterioma_engine_qa
        stdin_open: true
        tty: true
        environment:
            - PHPQA_HOME_DIR=/phpqa
            - PHPQA_CODE_DIR=${PHPQA_HOME_DIR}/code
            - PHPQA_LOGS_DIR=${PHPQA_HOME_DIR}/logs
            - PHPQA_TEST_DIR=${PHPQA_HOME_DIR}/code
        volumes:
          - ./src:/code
          - ./.docker/qa-results:/logs